### ISSUE TITLE
Login fails silently on insufficient read permissions 

### ISSUE THREAD

**Issue by twschiller** [etianen/django-python3-ldap#59] opened 2017-02-14 02:00 UTC
The login fails silently when the bound user doesn't have permission to read the attributes of the bound user object during login.

The OpenLDAP logs show a 32 error code when this occurs. I haven't checked whether the response from the OpenLDAP sever includes the error code, though:
  
     SEARCH RESULT tag=101 err=32 nentries=0 text=

It would be useful for django-python3-ldap to log a warning when this occurs (e.g.,  similar to the one for invalid credentials), as the error likely signals a configuration problem.

**Comment by etianen** [comment] 2017-02-14 10:34
The LDAP connection is configured to raise an exception in the event of an error, and such an exception is then logged by django-python3-ldap. I guess this means that the LDAP connection isn't raising an exception for this error.

I'll happily take a pull request that fixes this for you. I'm afraid that it's not something I can reproduce myself without messing around with the company LDAP server.

**Comment by twschiller** [comment] 2017-02-14 13:00
I ran into it by spinning up a Docker OpenLDAP server https://github.com/osixia/docker-openldap, which doesn't have the read access set up by default for the bound user

I probably won't be able to put together a PR for awhile, but just wanted to record the issue in case anyone ran into the problem

**Comment by etianen** [comment] 2017-02-14 13:06
No worries. Documenting the issue is a good step in the right direction.: )

**Comment by etianen** [comment] 2017-04-12 10:16
This is now fixed in master. If you hardcode `LDAP_AUTH_CONNECTION_USERNAME` and `LDAP_AUTH_CONNECTION_PASSWORD` in your settings, then that user will be used for querying the LDAP database after the initial bind() operation.

**Closed by etianen** 2017-04-12 10:16 UTC
