### ISSUE TITLE
ldap_sync_users completes successfully, still can't login

### ISSUE THREAD

**Issue by alanzoppa** [etianen/django-python3-ldap#16] opened 2015-08-03 22:44 UTC
Hi there! Thanks for developing this.

I'm able to run ldap_sync_users and get the accounts that I expect. After doing so, I manually set is_staff and is_superuser to True for my own account and tried to login to the admin interface. All I get is the standard "Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive."

I'm at a loss for where to start debugging. Can you suggest something, even a function I can monkey-patch and debug?

**Comment by etianen** [comment] 2015-08-04 10:27
This is a duplicate of #12 (which I've just renamed, since it's title was no longer relevant.

Let's continue the discussion there! Hopefully your input will help solve the issue!

**Closed by etianen** 2015-08-04 10:27 UTC
